// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
#![allow(clippy::missing_safety_doc, clippy::not_unsafe_ptr_arg_deref)]
use crate::bind;
use deno_bindgen::deno_bindgen;

/// Status-tag a BindResult: `0` + payload on success, `1` + error JSON on error.
fn tag(r: bind::BindResult) -> String {
    match r {
        Ok(payload) => format!("0{payload}"),
        Err(e) => format!(
            "1{}",
            serde_json::to_string(&e).unwrap_or_else(|_| "{}".into())
        ),
    }
}

#[deno_bindgen]
pub fn aa_version() -> String {
    tag(bind::version())
}

#[deno_bindgen]
pub fn aa_doctor(root: &str) -> String {
    tag(bind::doctor(root))
}

#[deno_bindgen]
pub fn aa_analyze(root: &str) -> String {
    tag(bind::analyze(root))
}

#[deno_bindgen]
pub fn aa_init(root: &str) -> String {
    tag(bind::init(root))
}

#[deno_bindgen]
pub fn aa_apply(root: &str, plan_path: &str, approve: u8) -> String {
    tag(bind::apply(root, plan_path, approve != 0))
}

#[deno_bindgen]
pub fn aa_revert(root: &str, run_id: &str) -> String {
    tag(bind::revert(root, run_id))
}

#[deno_bindgen]
pub fn aa_run_sync(root: &str, objective: &str, from: &str, approve: u8) -> String {
    let from = if from.is_empty() { None } else { Some(from) };
    tag(bind::run_sync(root, objective, from, approve != 0))
}

#[deno_bindgen]
pub fn aa_evolve_sync(root: &str, objective: &str, from: &str, apply: u8) -> String {
    let from = if from.is_empty() { None } else { Some(from) };
    tag(bind::evolve_sync(root, objective, from, apply != 0))
}

#[deno_bindgen]
pub fn aa_patch_list(root: &str) -> String {
    tag(bind::patch_list(root))
}

#[deno_bindgen]
pub fn aa_patch_show(root: &str, run_id: &str) -> String {
    tag(bind::patch_show(root, run_id))
}

#[deno_bindgen]
pub fn aa_config_show(root: &str) -> String {
    tag(bind::config_show(root))
}

#[deno_bindgen]
pub fn aa_memory_show(root: &str) -> String {
    tag(bind::memory_show(root))
}

#[deno_bindgen]
pub fn aa_tools_list(root: &str) -> String {
    tag(bind::tools_list(root))
}

#[deno_bindgen(non_blocking)]
pub fn aa_run(root: &str, objective: &str, from: &str, approve: u8) -> String {
    let from = if from.is_empty() { None } else { Some(from) };
    tag(bind::run_sync(root, objective, from, approve != 0))
}

#[deno_bindgen(non_blocking)]
pub fn aa_evolve(root: &str, objective: &str, from: &str, apply: u8) -> String {
    let from = if from.is_empty() { None } else { Some(from) };
    tag(bind::evolve_sync(root, objective, from, apply != 0))
}
