// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
use crate::bind;
use std::ffi::{c_char, CStr, CString};

/// Borrow a C string as `&str` (empty if null/invalid).
unsafe fn cs<'a>(p: *const c_char) -> &'a str {
    if p.is_null() {
        ""
    } else {
        CStr::from_ptr(p).to_str().unwrap_or("")
    }
}

/// Borrow an optional C string (`None` if null).
unsafe fn opt<'a>(p: *const c_char) -> Option<&'a str> {
    if p.is_null() {
        None
    } else {
        CStr::from_ptr(p).to_str().ok()
    }
}

/// Encode a BindResult as an owned, status-tagged C string the caller must free
/// with `aa_free`: `0` + payload on success, `1` + serialized BindError on error.
fn out(r: bind::BindResult) -> *mut c_char {
    let tagged = match r {
        Ok(payload) => format!("0{payload}"),
        Err(e) => format!("1{}", serde_json::to_string(&e).unwrap_or_else(|_| "{}".into())),
    };
    CString::new(tagged).unwrap_or_default().into_raw()
}

/// Free a string returned by any `aa_*` function.
#[no_mangle]
pub unsafe extern "C" fn aa_free(p: *mut c_char) {
    if !p.is_null() {
        drop(CString::from_raw(p));
    }
}

#[no_mangle]
pub unsafe extern "C" fn aa_version() -> *mut c_char {
    out(bind::version())
}

#[no_mangle]
pub unsafe extern "C" fn aa_doctor(root: *const c_char) -> *mut c_char {
    out(bind::doctor(cs(root)))
}

#[no_mangle]
pub unsafe extern "C" fn aa_analyze(root: *const c_char) -> *mut c_char {
    out(bind::analyze(cs(root)))
}

#[no_mangle]
pub unsafe extern "C" fn aa_init(root: *const c_char) -> *mut c_char {
    out(bind::init(cs(root)))
}

#[no_mangle]
pub unsafe extern "C" fn aa_apply(root: *const c_char, plan_path: *const c_char, approve: i32) -> *mut c_char {
    out(bind::apply(cs(root), cs(plan_path), approve != 0))
}

#[no_mangle]
pub unsafe extern "C" fn aa_revert(root: *const c_char, run_id: *const c_char) -> *mut c_char {
    out(bind::revert(cs(root), cs(run_id)))
}

#[no_mangle]
pub unsafe extern "C" fn aa_run_sync(root: *const c_char, objective: *const c_char, from: *const c_char, approve: i32) -> *mut c_char {
    out(bind::run_sync(cs(root), cs(objective), opt(from), approve != 0))
}

#[no_mangle]
pub unsafe extern "C" fn aa_evolve_sync(root: *const c_char, objective: *const c_char, from: *const c_char, apply: i32) -> *mut c_char {
    out(bind::evolve_sync(cs(root), cs(objective), opt(from), apply != 0))
}

#[no_mangle]
pub unsafe extern "C" fn aa_patch_list(root: *const c_char) -> *mut c_char {
    out(bind::patch_list(cs(root)))
}

#[no_mangle]
pub unsafe extern "C" fn aa_patch_show(root: *const c_char, run_id: *const c_char) -> *mut c_char {
    out(bind::patch_show(cs(root), cs(run_id)))
}

#[no_mangle]
pub unsafe extern "C" fn aa_config_show(root: *const c_char) -> *mut c_char {
    out(bind::config_show(cs(root)))
}

#[no_mangle]
pub unsafe extern "C" fn aa_memory_show(root: *const c_char) -> *mut c_char {
    out(bind::memory_show(cs(root)))
}

#[no_mangle]
pub unsafe extern "C" fn aa_tools_list(root: *const c_char) -> *mut c_char {
    out(bind::tools_list(cs(root)))
}

