// DO NOT EDIT — generated by autoagent-bingen from core JsonSchema.
export interface Check {
  detail: string;
  name: string;
  ok: boolean;
}

export interface CommandValidationResult {
  command: string;
  duration_ms: number;
  exit_code: number | null;
  stderr: string;
  stdout: string;
}

export interface DependencySummary {
  dev: boolean;
  name: string;
  version: string;
}

export interface DoctorReport {
  checks: Check[];
}

export interface EvolveOutcome {
  applied: boolean;
  branch: string | null;
  plan_path: string;
  run_id: string | null;
}

export type LanguageKind = "Rust" | "JavaScript" | "TypeScript" | "Mixed" | "Unknown";

export interface MemorySummary {
  decisions: number;
  language: string;
  name: string;
  package_manager: string | null;
  source_file_count: number;
}

export type PackageManager = "Cargo" | "Npm" | "Pnpm" | "Yarn";

export interface ProjectAnalysis {
  dependencies: DependencySummary[];
  file_count: number;
  language: LanguageKind;
  package_manager: PackageManager | null;
  root: string;
  source_files: number;
  top_dirs: string[];
}

export interface RunOutcome {
  final_state: RunState;
  report: ValidationReport;
  run_id: string;
}

export type RunState = "Created" | "LoadingConfig" | "AnalyzingProject" | "LoadingMemory" | "Planning" | "AwaitingApproval" | "Snapshotting" | "ApplyingChanges" | "Validating" | "Repairing" | "Completed" | "Failed" | "Reverted";

export interface ValidationReport {
  commands: CommandValidationResult[];
  passed: boolean;
}

