// Generate the deno_bindgen TypeScript bindings (`bindings/bindings.ts`) using
// deno_bindgen's own `codegen()`.
//
// We call codegen() directly instead of the `deno_bindgen` CLI because that
// CLI's metadata discovery (OUT_DIR || workspace_root) breaks for a crate that
// is both a Cargo workspace member AND has a build.rs — the macro emits
// bindings.json into the per-build OUT_DIR, which the CLI never looks in. This
// reuses the recommended generator with the correct paths.
//
// Usage: deno run -A deno/gen.ts <path-to-bindings.json> <dylib-prefix>
//   e.g. deno run -A deno/gen.ts \
//          ../../target/debug/build/autoagent-bingen-*/out/bindings.json \
//          ../../../target/debug

import { codegen } from "https://deno.land/x/deno_bindgen/codegen.ts";

const metaPath = Deno.args[0];
const fetchPrefix = Deno.args[1];
if (!metaPath || !fetchPrefix) {
  console.error("usage: gen.ts <bindings.json> <dylib-dir-prefix>");
  Deno.exit(2);
}

const conf = JSON.parse(await Deno.readTextFile(metaPath));

const source = "// DO NOT EDIT — generated by deno_bindgen (deno/gen.ts).\n" +
  codegen(
    fetchPrefix,
    conf.name,
    conf.typeDefs,
    conf.tsTypes,
    conf.symbols,
    { le: conf.littleEndian, release: false, releaseURL: undefined },
  );

// Write to the crate-root `bindings/` (standard deno_bindgen layout).
await Deno.mkdir(new URL("../bindings", import.meta.url), { recursive: true });
await Deno.writeTextFile(new URL("../bindings/bindings.ts", import.meta.url), source);
console.log(`wrote bindings/bindings.ts (${Object.keys(conf.symbols).length} symbols)`);
