// DO NOT EDIT — generated by autoagent-bingen.
// Deno FFI binding for autoagent-core. Requires --allow-ffi (and
// --allow-read/--allow-write for mutating ops). Set AUTOAGENT_BINGEN_LIB to the
// built cdylib, or place it under ../../target/release relative to this file.
import type {
  DoctorReport,
  EvolveOutcome,
  MemorySummary,
  ProjectAnalysis,
  RunOutcome,
} from "./_models.ts";

const ext = Deno.build.os === "darwin" ? "dylib" : Deno.build.os === "windows" ? "dll" : "so";
const prefix = Deno.build.os === "windows" ? "" : "lib";
const defaultLib = new URL(`../../../target/release/${prefix}autoagent_bingen.${ext}`, import.meta.url).pathname;
const libPath = Deno.env.get("AUTOAGENT_BINGEN_LIB") ?? defaultLib;

const lib = Deno.dlopen(libPath, {
  aa_free: { parameters: ["pointer"], result: "void" },
  aa_version: { parameters: [], result: "pointer" },
  aa_doctor: { parameters: ["pointer"], result: "pointer" },
  aa_analyze: { parameters: ["pointer"], result: "pointer" },
  aa_init: { parameters: ["pointer"], result: "pointer" },
  aa_apply: { parameters: ["pointer", "pointer", "i32"], result: "pointer" },
  aa_revert: { parameters: ["pointer", "pointer"], result: "pointer" },
  aa_run_sync: { parameters: ["pointer", "pointer", "pointer", "i32"], result: "pointer" },
  aa_evolve_sync: { parameters: ["pointer", "pointer", "pointer", "i32"], result: "pointer" },
  aa_patch_list: { parameters: ["pointer"], result: "pointer" },
  aa_patch_show: { parameters: ["pointer", "pointer"], result: "pointer" },
  aa_config_show: { parameters: ["pointer"], result: "pointer" },
  aa_memory_show: { parameters: ["pointer"], result: "pointer" },
  aa_tools_list: { parameters: ["pointer"], result: "pointer" },
} as const);

const _enc = new TextEncoder();
function cstr(s: string): Uint8Array { return _enc.encode(s + "\0"); }
function ptr(buf: Uint8Array): Deno.PointerValue {
  // TextEncoder always allocates a plain ArrayBuffer (never SharedArrayBuffer);
  // assert it for Deno's strict UnsafePointer.of signature.
  return Deno.UnsafePointer.of(buf as Uint8Array<ArrayBuffer>);
}

export class AutoAgentError extends Error {
  code: string;
  exitCode: number;
  constructor(message: string, code: string, exitCode: number) {
    super(message);
    this.name = "AutoAgentError";
    this.code = code;
    this.exitCode = exitCode;
  }
}

function take(p: Deno.PointerValue): string {
  if (p === null) return "";
  const s = new Deno.UnsafePointerView(p).getCString();
  lib.symbols.aa_free(p);
  return s;
}

function unwrap(tagged: string): string {
  const tag = tagged.charAt(0);
  const body = tagged.slice(1);
  if (tag === "1") {
    const e = JSON.parse(body);
    throw new AutoAgentError(e.message, e.code, e.exit_code);
  }
  return body;
}

export function version(): number {
  const body = unwrap(take(lib.symbols.aa_version()));
  return Number(body);
}

export function doctor(root: string): DoctorReport {
  const body = unwrap(take(lib.symbols.aa_doctor(ptr(cstr(root)))));
  return JSON.parse(body);
}

export function analyze(root: string): ProjectAnalysis {
  const body = unwrap(take(lib.symbols.aa_analyze(ptr(cstr(root)))));
  return JSON.parse(body);
}

export function init(root: string): boolean {
  const body = unwrap(take(lib.symbols.aa_init(ptr(cstr(root)))));
  return body === "true";
}

export function apply(root: string, plan_path: string, approve: boolean): string {
  const body = unwrap(take(lib.symbols.aa_apply(ptr(cstr(root)), ptr(cstr(plan_path)), approve ? 1 : 0)));
  return body;
}

export function revert(root: string, run_id: string): void {
  const body = unwrap(take(lib.symbols.aa_revert(ptr(cstr(root)), ptr(cstr(run_id)))));
  return;
}

export function runSync(root: string, objective: string, from: string | null, approve: boolean): RunOutcome {
  const body = unwrap(take(lib.symbols.aa_run_sync(ptr(cstr(root)), ptr(cstr(objective)), from == null ? null : ptr(cstr(from)), approve ? 1 : 0)));
  return JSON.parse(body);
}

export function evolveSync(root: string, objective: string, from: string | null, apply: boolean): EvolveOutcome {
  const body = unwrap(take(lib.symbols.aa_evolve_sync(ptr(cstr(root)), ptr(cstr(objective)), from == null ? null : ptr(cstr(from)), apply ? 1 : 0)));
  return JSON.parse(body);
}

export function patchList(root: string): string[] {
  const body = unwrap(take(lib.symbols.aa_patch_list(ptr(cstr(root)))));
  return JSON.parse(body);
}

export function patchShow(root: string, run_id: string): string {
  const body = unwrap(take(lib.symbols.aa_patch_show(ptr(cstr(root)), ptr(cstr(run_id)))));
  return body;
}

export function configShow(root: string): string {
  const body = unwrap(take(lib.symbols.aa_config_show(ptr(cstr(root)))));
  return body;
}

export function memoryShow(root: string): MemorySummary {
  const body = unwrap(take(lib.symbols.aa_memory_show(ptr(cstr(root)))));
  return JSON.parse(body);
}

export function toolsList(root: string): string[] {
  const body = unwrap(take(lib.symbols.aa_tools_list(ptr(cstr(root)))));
  return JSON.parse(body);
}

