// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
use napi_derive::napi;
use crate::bind;

fn to_napi(e: bind::BindError) -> napi::Error {
    napi::Error::new(
        napi::Status::GenericFailure,
        format!("[{}|{}] {}", e.code, e.exit_code, e.message),
    )
}

fn parse(j: String) -> napi::Result<serde_json::Value> {
    serde_json::from_str(&j).map_err(|e| napi::Error::from_reason(e.to_string()))
}

#[napi]
pub fn version() -> napi::Result<u32> {
    bind::version()
        .map(|v| v.trim().parse().unwrap_or(0))
        .map_err(to_napi)
}

#[napi(ts_return_type = "DoctorReport")]
pub fn doctor(root: String) -> napi::Result<serde_json::Value> {
    let j = bind::doctor(&root).map_err(to_napi)?;
    parse(j)
}

#[napi(ts_return_type = "ProjectAnalysis")]
pub fn analyze(root: String) -> napi::Result<serde_json::Value> {
    let j = bind::analyze(&root).map_err(to_napi)?;
    parse(j)
}

