// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
use crate::bind;
use napi_derive::napi;

fn to_napi(e: bind::BindError) -> napi::Error {
    napi::Error::new(
        napi::Status::GenericFailure,
        format!("[{}|{}] {}", e.code, e.exit_code, e.message),
    )
}

fn parse(j: String) -> napi::Result<serde_json::Value> {
    serde_json::from_str(&j).map_err(|e| napi::Error::from_reason(e.to_string()))
}

#[napi(js_name = "version")]
pub fn version() -> napi::Result<u32> {
    bind::version()
        .map(|v| v.trim().parse().unwrap_or(0))
        .map_err(to_napi)
}

#[napi(js_name = "doctor", ts_return_type = "DoctorReport")]
pub fn doctor(root: String) -> napi::Result<serde_json::Value> {
    let j = bind::doctor(&root).map_err(to_napi)?;
    parse(j)
}

#[napi(js_name = "analyze", ts_return_type = "ProjectAnalysis")]
pub fn analyze(root: String) -> napi::Result<serde_json::Value> {
    let j = bind::analyze(&root).map_err(to_napi)?;
    parse(j)
}

#[napi(js_name = "init")]
pub fn init(root: String) -> napi::Result<bool> {
    bind::init(&root)
        .map(|v| v.trim() == "true")
        .map_err(to_napi)
}

#[napi(js_name = "apply")]
pub fn apply(root: String, plan_path: String, approve: bool) -> napi::Result<String> {
    bind::apply(&root, &plan_path, approve).map_err(to_napi)
}

#[napi(js_name = "revert")]
pub fn revert(root: String, run_id: String) -> napi::Result<()> {
    bind::revert(&root, &run_id).map(|_| ()).map_err(to_napi)
}

#[napi(js_name = "replay", ts_return_type = "RunOutcome")]
pub fn replay(root: String, session_id: String, approve: bool) -> napi::Result<serde_json::Value> {
    let j = bind::replay(&root, &session_id, approve).map_err(to_napi)?;
    parse(j)
}

#[napi(js_name = "runSync", ts_return_type = "RunOutcome")]
pub fn run_sync(
    root: String,
    objective: String,
    from: Option<String>,
    approve: bool,
) -> napi::Result<serde_json::Value> {
    let j = bind::run_sync(&root, &objective, from.as_deref(), approve).map_err(to_napi)?;
    parse(j)
}

#[napi(js_name = "evolveSync", ts_return_type = "EvolveOutcome")]
pub fn evolve_sync(
    root: String,
    objective: String,
    from: Option<String>,
    apply: bool,
) -> napi::Result<serde_json::Value> {
    let j = bind::evolve_sync(&root, &objective, from.as_deref(), apply).map_err(to_napi)?;
    parse(j)
}

#[napi(js_name = "patchList", ts_return_type = "string[]")]
pub fn patch_list(root: String) -> napi::Result<serde_json::Value> {
    let j = bind::patch_list(&root).map_err(to_napi)?;
    parse(j)
}

#[napi(js_name = "patchShow")]
pub fn patch_show(root: String, run_id: String) -> napi::Result<String> {
    bind::patch_show(&root, &run_id).map_err(to_napi)
}

#[napi(js_name = "configShow")]
pub fn config_show(root: String) -> napi::Result<String> {
    bind::config_show(&root).map_err(to_napi)
}

#[napi(js_name = "memoryShow", ts_return_type = "MemorySummary")]
pub fn memory_show(root: String) -> napi::Result<serde_json::Value> {
    let j = bind::memory_show(&root).map_err(to_napi)?;
    parse(j)
}

#[napi(js_name = "toolsList", ts_return_type = "string[]")]
pub fn tools_list(root: String) -> napi::Result<serde_json::Value> {
    let j = bind::tools_list(&root).map_err(to_napi)?;
    parse(j)
}

#[napi(js_name = "run", ts_return_type = "Promise<RunOutcome>")]
pub async fn run(
    root: String,
    objective: String,
    from: Option<String>,
    approve: bool,
) -> napi::Result<serde_json::Value> {
    let j = napi::tokio::task::spawn_blocking(move || {
        bind::run_sync(&root, &objective, from.as_deref(), approve)
    })
    .await
    .map_err(|e| napi::Error::from_reason(e.to_string()))?
    .map_err(to_napi)?;
    parse(j)
}

#[napi(js_name = "evolve", ts_return_type = "Promise<EvolveOutcome>")]
pub async fn evolve(
    root: String,
    objective: String,
    from: Option<String>,
    apply: bool,
) -> napi::Result<serde_json::Value> {
    let j = napi::tokio::task::spawn_blocking(move || {
        bind::evolve_sync(&root, &objective, from.as_deref(), apply)
    })
    .await
    .map_err(|e| napi::Error::from_reason(e.to_string()))?
    .map_err(to_napi)?;
    parse(j)
}
