// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
#![allow(clippy::missing_safety_doc, clippy::not_unsafe_ptr_arg_deref)]
use crate::bind;
use node_bindgen::derive::node_bindgen;

fn tag(r: bind::BindResult) -> String {
    match r {
        Ok(payload) => format!("0{payload}"),
        Err(e) => format!(
            "1{}",
            serde_json::to_string(&e).unwrap_or_else(|_| "{}".into())
        ),
    }
}

// Modern N-API entry point. nj-core 6.1 only registers via an old `#[ctor]`
// (`napi_module_register`) that Node 18+ no longer honours. nj-core's
// `init_modules` is `#[no_mangle] extern "C"` but not reachable by Rust path
// (private module), so we link to it as a C symbol. Node looks up
// `napi_register_module_v1` on load; delegating here installs the annotated
// functions. Build with `-C link-dead-code` so the per-function registration
// constructors survive the cdylib's `-dead_strip`.
extern "C" {
    fn init_modules(
        env: node_bindgen::sys::napi_env,
        exports: node_bindgen::sys::napi_value,
    ) -> node_bindgen::sys::napi_value;
}

#[no_mangle]
pub unsafe extern "C" fn napi_register_module_v1(
    env: node_bindgen::sys::napi_env,
    exports: node_bindgen::sys::napi_value,
) -> node_bindgen::sys::napi_value {
    init_modules(env, exports)
}

#[node_bindgen(name = "version")]
fn version() -> String {
    tag(bind::version())
}

#[node_bindgen(name = "doctor")]
fn doctor(root: String) -> String {
    tag(bind::doctor(&root))
}

#[node_bindgen(name = "analyze")]
fn analyze(root: String) -> String {
    tag(bind::analyze(&root))
}

#[node_bindgen(name = "init")]
fn init(root: String) -> String {
    tag(bind::init(&root))
}

#[node_bindgen(name = "apply")]
fn apply(root: String, plan_path: String, approve: bool) -> String {
    tag(bind::apply(&root, &plan_path, approve))
}

#[node_bindgen(name = "revert")]
fn revert(root: String, run_id: String) -> String {
    tag(bind::revert(&root, &run_id))
}

#[node_bindgen(name = "replay")]
fn replay(root: String, session_id: String, approve: bool) -> String {
    tag(bind::replay(&root, &session_id, approve))
}

#[node_bindgen(name = "runSync")]
fn run_sync(root: String, objective: String, from: Option<String>, approve: bool) -> String {
    tag(bind::run_sync(&root, &objective, from.as_deref(), approve))
}

#[node_bindgen(name = "evolveSync")]
fn evolve_sync(root: String, objective: String, from: Option<String>, apply: bool) -> String {
    tag(bind::evolve_sync(&root, &objective, from.as_deref(), apply))
}

#[node_bindgen(name = "patchList")]
fn patch_list(root: String) -> String {
    tag(bind::patch_list(&root))
}

#[node_bindgen(name = "patchShow")]
fn patch_show(root: String, run_id: String) -> String {
    tag(bind::patch_show(&root, &run_id))
}

#[node_bindgen(name = "configShow")]
fn config_show(root: String) -> String {
    tag(bind::config_show(&root))
}

#[node_bindgen(name = "memoryShow")]
fn memory_show(root: String) -> String {
    tag(bind::memory_show(&root))
}

#[node_bindgen(name = "toolsList")]
fn tools_list(root: String) -> String {
    tag(bind::tools_list(&root))
}
