// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
// AutoAgent — typed Deno SDK over the native FFI binding.
//
// The native binding (`@autoagent/native`) already returns typed models and
// throws `AutoAgentError`; this module re-exports that functional API with the
// SDK's models + error type and adds the `AutoAgent` client class. Requires
// --allow-ffi (and --allow-read/--allow-write for mutating ops); set
// AUTOAGENT_BINGEN_LIB to the built cdylib.
//
// NOTE: the FFI binding is synchronous; this SDK surfaces the `*Sync` workflow
// entrypoints (awaitable run/evolve are available via the deno_bindgen path).

export * from "./_models.ts";
export { AutoAgentError } from "./errors.ts";
export { AutoAgent } from "./client.ts";

export {
  analyze,
  apply,
  configShow,
  doctor,
  evolveSync,
  init,
  memoryShow,
  patchList,
  patchShow,
  replay,
  revert,
  runSync,
  toolsList,
  version,
} from "../../crates/autoagent-bingen/deno/mod.ts";
