// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
use pyo3::prelude::*;
use crate::bind;

pyo3::create_exception!(autoagent, AutoAgentError, pyo3::exceptions::PyException);

fn to_py(e: bind::BindError) -> PyErr {
    AutoAgentError::new_err(format!("[{}|{}] {}", e.code, e.exit_code, e.message))
}

#[pyfunction]
fn version() -> PyResult<u32> {
    bind::version().map(|v| v.trim().parse().unwrap_or(0)).map_err(to_py)
}

#[pyfunction]
fn doctor(root: String) -> PyResult<String> {
    bind::doctor(&root).map_err(to_py)
}

#[pyfunction]
fn analyze(root: String) -> PyResult<String> {
    bind::analyze(&root).map_err(to_py)
}

#[pyfunction]
fn init(root: String) -> PyResult<bool> {
    bind::init(&root).map(|v| v.trim() == "true").map_err(to_py)
}

#[pyfunction]
fn patch_list(root: String) -> PyResult<String> {
    bind::patch_list(&root).map_err(to_py)
}

#[pyfunction]
fn patch_show(root: String, run_id: String) -> PyResult<String> {
    bind::patch_show(&root, &run_id).map_err(to_py)
}

#[pyfunction]
fn config_show(root: String) -> PyResult<String> {
    bind::config_show(&root).map_err(to_py)
}

#[pyfunction]
fn memory_show(root: String) -> PyResult<String> {
    bind::memory_show(&root).map_err(to_py)
}

#[pyfunction]
fn tools_list(root: String) -> PyResult<String> {
    bind::tools_list(&root).map_err(to_py)
}

#[pymodule]
fn autoagent(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add("AutoAgentError", m.py().get_type::<AutoAgentError>())?;
    m.add_function(wrap_pyfunction!(version, m)?)?;
    m.add_function(wrap_pyfunction!(doctor, m)?)?;
    m.add_function(wrap_pyfunction!(analyze, m)?)?;
    m.add_function(wrap_pyfunction!(init, m)?)?;
    m.add_function(wrap_pyfunction!(patch_list, m)?)?;
    m.add_function(wrap_pyfunction!(patch_show, m)?)?;
    m.add_function(wrap_pyfunction!(config_show, m)?)?;
    m.add_function(wrap_pyfunction!(memory_show, m)?)?;
    m.add_function(wrap_pyfunction!(tools_list, m)?)?;
    Ok(())
}
