// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
//! RustPython native module exposing the autoagent surface (CPython-free path).
//! Install it with:
//!   let builder = rustpython_vm::Interpreter::builder(Default::default());
//!   let def = autoagent_bingen::python::python_bingen::module_def(&builder.ctx);
//!   builder.add_native_module(def).build().enter(|vm| { /* import autoagent */ });

/// Public accessor for the native module definition (the `#[pymodule]` macro's
/// own `module_def` is `pub(crate)` and cannot be re-exported).
pub fn module_def(
    ctx: &rustpython_vm::Context,
) -> &'static rustpython_vm::builtins::PyModuleDef {
    autoagent::module_def(ctx)
}

#[rustpython_vm::pymodule]
mod autoagent {
    use crate::bind;
    use rustpython_vm::{builtins::PyBaseExceptionRef, PyResult, VirtualMachine};

    fn err(e: bind::BindError, vm: &VirtualMachine) -> PyBaseExceptionRef {
        vm.new_runtime_error(format!("[{}|{}] {}", e.code, e.exit_code, e.message))
    }

    #[pyfunction]
    fn version(vm: &VirtualMachine) -> PyResult<u32> {
        bind::version().map(|v| v.trim().parse().unwrap_or(0)).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn doctor(root: String, vm: &VirtualMachine) -> PyResult<String> {
        bind::doctor(&root).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn analyze(root: String, vm: &VirtualMachine) -> PyResult<String> {
        bind::analyze(&root).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn init(root: String, vm: &VirtualMachine) -> PyResult<bool> {
        bind::init(&root).map(|v| v.trim() == "true").map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn apply(root: String, plan_path: String, approve: bool, vm: &VirtualMachine) -> PyResult<String> {
        bind::apply(&root, &plan_path, approve).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn revert(root: String, run_id: String, vm: &VirtualMachine) -> PyResult<()> {
        bind::revert(&root, &run_id).map(|_| ()).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn run_sync(root: String, objective: String, from: Option<String>, approve: bool, vm: &VirtualMachine) -> PyResult<String> {
        bind::run_sync(&root, &objective, from.as_deref(), approve).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn evolve_sync(root: String, objective: String, from: Option<String>, apply: bool, vm: &VirtualMachine) -> PyResult<String> {
        bind::evolve_sync(&root, &objective, from.as_deref(), apply).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn patch_list(root: String, vm: &VirtualMachine) -> PyResult<String> {
        bind::patch_list(&root).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn patch_show(root: String, run_id: String, vm: &VirtualMachine) -> PyResult<String> {
        bind::patch_show(&root, &run_id).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn config_show(root: String, vm: &VirtualMachine) -> PyResult<String> {
        bind::config_show(&root).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn memory_show(root: String, vm: &VirtualMachine) -> PyResult<String> {
        bind::memory_show(&root).map_err(|e| err(e, vm))
    }

    #[pyfunction]
    fn tools_list(root: String, vm: &VirtualMachine) -> PyResult<String> {
        bind::tools_list(&root).map_err(|e| err(e, vm))
    }

}
