# DO NOT EDIT — generated by autoagent-bingen from core JsonSchema.
from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Literal, Optional

@dataclass
class Check:
    detail: str
    name: str
    ok: bool

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Check":
        return cls(
            detail=d.get("detail"),
            name=d.get("name"),
            ok=d.get("ok"),
        )

@dataclass
class CommandValidationResult:
    command: str
    duration_ms: int
    exit_code: Optional[int]
    stderr: str
    stdout: str

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "CommandValidationResult":
        return cls(
            command=d.get("command"),
            duration_ms=d.get("duration_ms"),
            exit_code=d.get("exit_code"),
            stderr=d.get("stderr"),
            stdout=d.get("stdout"),
        )

@dataclass
class DependencySummary:
    dev: bool
    name: str
    version: str

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "DependencySummary":
        return cls(
            dev=d.get("dev"),
            name=d.get("name"),
            version=d.get("version"),
        )

@dataclass
class DoctorReport:
    checks: list[Check]

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "DoctorReport":
        return cls(
            checks=[Check.from_dict(_x) for _x in d.get("checks")],
        )

@dataclass
class EvolveOutcome:
    applied: bool
    branch: Optional[str]
    plan_path: str
    run_id: Optional[str]

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "EvolveOutcome":
        return cls(
            applied=d.get("applied"),
            branch=d.get("branch"),
            plan_path=d.get("plan_path"),
            run_id=d.get("run_id"),
        )

LanguageKind = Literal["Rust", "JavaScript", "TypeScript", "Mixed", "Unknown"]

@dataclass
class MemorySummary:
    decisions: int
    language: str
    name: str
    package_manager: Optional[str]
    source_file_count: int

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "MemorySummary":
        return cls(
            decisions=d.get("decisions"),
            language=d.get("language"),
            name=d.get("name"),
            package_manager=d.get("package_manager"),
            source_file_count=d.get("source_file_count"),
        )

PackageManager = Literal["Cargo", "Npm", "Pnpm", "Yarn"]

@dataclass
class ProjectAnalysis:
    dependencies: list[DependencySummary]
    file_count: int
    language: LanguageKind
    package_manager: Optional[PackageManager]
    root: str
    source_files: int
    top_dirs: list[str]

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "ProjectAnalysis":
        return cls(
            dependencies=[DependencySummary.from_dict(_x) for _x in d.get("dependencies")],
            file_count=d.get("file_count"),
            language=d.get("language"),
            package_manager=d.get("package_manager"),
            root=d.get("root"),
            source_files=d.get("source_files"),
            top_dirs=d.get("top_dirs"),
        )

@dataclass
class RunOutcome:
    final_state: RunState
    report: ValidationReport
    run_id: str

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "RunOutcome":
        return cls(
            final_state=d.get("final_state"),
            report=ValidationReport.from_dict(d.get("report")),
            run_id=d.get("run_id"),
        )

RunState = Literal["Created", "LoadingConfig", "AnalyzingProject", "LoadingMemory", "Planning", "AwaitingApproval", "Snapshotting", "ApplyingChanges", "Validating", "Repairing", "Completed", "Failed", "Reverted"]

@dataclass
class ValidationReport:
    commands: list[CommandValidationResult]
    passed: bool

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "ValidationReport":
        return cls(
            commands=[CommandValidationResult.from_dict(_x) for _x in d.get("commands")],
            passed=d.get("passed"),
        )

