// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
// The AutoAgent client class — sugar over the functional API that holds the
// workspace root so callers pass it once.

import {
  analyze,
  apply,
  configShow,
  doctor,
  evolve,
  evolveSync,
  init,
  memoryShow,
  patchList,
  patchShow,
  replay,
  revert,
  run,
  runSync,
  toolsList,
} from "./index.js";
import type {
  DoctorReport,
  EvolveOutcome,
  MemorySummary,
  ProjectAnalysis,
  RunOutcome,
} from "./_models.js";

/** A workspace-scoped client. `new AutoAgent('/repo').doctor()`. */
export class AutoAgent {
  constructor(public readonly root: string) {}

  doctor(): DoctorReport {
    return doctor(this.root);
  }
  analyze(): ProjectAnalysis {
    return analyze(this.root);
  }
  patchList(): string[] {
    return patchList(this.root);
  }
  patchShow(runId: string): string {
    return patchShow(this.root, runId);
  }
  configShow(): string {
    return configShow(this.root);
  }
  memoryShow(): MemorySummary {
    return memoryShow(this.root);
  }
  toolsList(): string[] {
    return toolsList(this.root);
  }
  init(): boolean {
    return init(this.root);
  }
  apply(planPath: string, approve = false): string {
    return apply(this.root, planPath, approve);
  }
  revert(runId: string): void {
    revert(this.root, runId);
  }
  replay(sessionId: string, approve = false): RunOutcome {
    return replay(this.root, sessionId, approve);
  }
  runSync(objective: string, from: string | null = null, approve = false): RunOutcome {
    return runSync(this.root, objective, from, approve);
  }
  evolveSync(objective: string, from: string | null = null, apply = false): EvolveOutcome {
    return evolveSync(this.root, objective, from, apply);
  }
  run(objective: string, from: string | null = null, approve = false): Promise<RunOutcome> {
    return run(this.root, objective, from, approve);
  }
  evolve(objective: string, from: string | null = null, apply = false): Promise<EvolveOutcome> {
    return evolve(this.root, objective, from, apply);
  }
}
