// DO NOT EDIT — generated by autoagent-bingen from bind.rs.
// AutoAgent — typed Node.js SDK over the native bindings (@autoagent-sdk/native).
// The native binding returns parsed objects (napi) and throws `[code|exitCode]`
// errors; this layer types the results with the generated models and maps
// errors to AutoAgentError. Mutating ops preserve fail-closed safety.

import nativeDefault from "@autoagent-sdk/native";
import { AutoAgentError } from "./errors.js";
import type {
  DoctorReport,
  EvolveOutcome,
  MemorySummary,
  ProjectAnalysis,
  RunOutcome,
} from "./_models.js";

export * from "./_models.js";
export { AutoAgentError };
export { AutoAgent } from "./client.js";

// @autoagent-sdk/native is the runtime bridge; the SDK supplies the real types via
// the generated models, so the native is consumed loosely and cast.
// deno-lint-ignore no-explicit-any
const native = nativeDefault as any;

function wrap<T>(fn: () => T): T {
  try {
    return fn();
  } catch (e) {
    throw AutoAgentError.fromNative(e);
  }
}

// --- read surface ---------------------------------------------------------

/** Schema version this build supports. */
export function version(): number {
  return native.version();
}

/** System, config, and workspace health checks. */
export function doctor(root: string): DoctorReport {
  return wrap(() => native.doctor(root)) as DoctorReport;
}

/** Analyze the project and write the report. */
export function analyze(root: string): ProjectAnalysis {
  return wrap(() => native.analyze(root)) as ProjectAnalysis;
}

/** List patch artifact run ids. */
export function patchList(root: string): string[] {
  return wrap(() => native.patchList(root));
}

/** Show a patch body. */
export function patchShow(root: string, runId: string): string {
  return wrap(() => native.patchShow(root, runId));
}

/** Render Autoagent.toml. */
export function configShow(root: string): string {
  return wrap(() => native.configShow(root));
}

/** Project memory summary. */
export function memoryShow(root: string): MemorySummary {
  return wrap(() => native.memoryShow(root)) as MemorySummary;
}

/** Registered plugin tools. */
export function toolsList(root: string): string[] {
  return wrap(() => native.toolsList(root));
}

// --- mutating surface (fail-closed) ---------------------------------------

/** Initialize Autoagent.toml and the .agent/ tree. */
export function init(root: string): boolean {
  return wrap(() => native.init(root));
}

/** Apply a plan through the policy engine; returns the run id. */
export function apply(root: string, planPath: string, approve = false): string {
  return wrap(() => native.apply(root, planPath, approve));
}

/** Revert a previous run. */
export function revert(root: string, runId: string): void {
  wrap(() => native.revert(root, runId));
}

/** Deterministically replay a recorded session, reproducing the run. */
export function replay(root: string, sessionId: string, approve = false): RunOutcome {
  return wrap(() => native.replay(root, sessionId, approve)) as RunOutcome;
}

/** Supervised run (blocking) from a plan or generated objective. */
export function runSync(root: string, objective: string, from: string | null = null, approve = false): RunOutcome {
  return wrap(() => native.runSync(root, objective, from, approve)) as RunOutcome;
}

/** Controlled self-authoring (blocking). */
export function evolveSync(root: string, objective: string, from: string | null = null, apply = false): EvolveOutcome {
  return wrap(() => native.evolveSync(root, objective, from, apply)) as EvolveOutcome;
}

/** Supervised plan -> apply -> validate -> repair -> report. */
export async function run(root: string, objective: string, from: string | null = null, approve = false): Promise<RunOutcome> {
  try {
    return (await native.run(root, objective, from, approve)) as RunOutcome;
  } catch (e) {
    throw AutoAgentError.fromNative(e);
  }
}

/** Controlled self-authoring plan (apply is policy-gated). */
export async function evolve(root: string, objective: string, from: string | null = null, apply = false): Promise<EvolveOutcome> {
  try {
    return (await native.evolve(root, objective, from, apply)) as EvolveOutcome;
  } catch (e) {
    throw AutoAgentError.fromNative(e);
  }
}

